### ISSUE TITLE
Buscar editores

### ISSUE THREAD

**Issue by aerendon** [labsirius/SiriusWebProject-Frontend#21]
e.g. Markdown, word. etc.

**Comment by leiverandres** [comment]
Estos me parecen bastante buenos:

* [Quill js](http://quilljs.com/) (Simple y bonito)
* [CKeditor](http://ckeditor.com/) (tiene más caracteristicas, pero sigue siendo simple. Además tiene edición inline)
* [TinyMCE](https://www.tinymce.com/) (Super completo y customizable)
